// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8TdAUMlMhHEYciA-RBnMdHU0zipuuqOA',
    appId: '1:763744361688:android:46675ad998fe7109c94bad',
    messagingSenderId: '763744361688',
    projectId: 'intrudersystem-6ed32',
    databaseURL: 'https://intrudersystem-6ed32-default-rtdb.firebaseio.com/',
    storageBucket: 'gs://intrudersystem-6ed32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdUK4BhKuWSnqOPnAR4T-xq2p7u2-qZPs',
    appId: '1:763744361688:ios:0514910d527866e2c94bad',
    messagingSenderId: '763744361688',
    projectId: 'intrudersystem-6ed32',
    databaseURL: 'https://intrudersystem-6ed32-default-rtdb.firebaseio.com',
    storageBucket: 'intrudersystem-6ed32.appspot.com',
    iosClientId: '763744361688-85ac0mi5v6svvo08cbf93uj5934a4mod.apps.googleusercontent.com',
    iosBundleId: 'intrudersystem',
  );
}
